apiVersion: v1	
kind: Service	
metadata:	
  labels:	
    app: averypage	
    app.kubernetes.io/instance: avery-app	
  managedFields:	
    - apiVersion: v1	
      fieldsType: FieldsV1	
      fieldsV1:	
        'f:metadata':	
          'f:labels':	
            .: {}	
            'f:app': {}	
            'f:app.kubernetes.io/instance': {}	
        'f:spec':	
          'f:internalTrafficPolicy': {}	
          'f:ports':	
            .: {}	
            'k:{"port":80,"protocol":"TCP"}':	
              .: {}	
              'f:port': {}	
              'f:protocol': {}	
              'f:targetPort': {}	
          'f:selector': {}	
          'f:sessionAffinity': {}	
          'f:type': {}	
      manager: kubectl-expose	
      operation: Update	
      time: '2022-01-24T04:48:02Z'	
  name: averypage	
  namespace: default	
  resourceVersion: '2292164'	
  uid: 2c26719d-099d-49a2-9c75-8e6cc764d6e4	
spec:	
  clusterIP: 10.106.12.93	
  clusterIPs:	
    - 10.106.12.93	
  internalTrafficPolicy: Cluster	
  ipFamilies:	
    - IPv4	
  ipFamilyPolicy: SingleStack	
  ports:	
    - port: 80	
      protocol: TCP	
      targetPort: 80	
  selector:	
    app: averypage	
  sessionAffinity: None	
  type: ClusterIP	
status:	
  loadBalancer: {}